name: Documentation

on:
  push:
    branches: [main]
    paths: [docs/**, .github/workflows/wiki_sync.yaml]
concurrency:
  group: wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: spenserblack/actions-wiki@main
        with:
          commit-message: ${{ github.event.pull_request.title }} (${{ github.event.number }})
          path: docs
